server:
  port: ${SERVER_PORT:8080}

grpc:
  client:
    identity-service:
      negotiation-type: plaintext

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-api-route
              uri: lb://identity-service
              predicates:
                - Path=/api/auth/**
              filters:
                - RewritePath=/api/auth/(?<segment>.*), /api/$\{segment}
            - id: identity-docs-route
              uri: lb://identity-service
              predicates:
                - Path=/docs/identity/{*segment}
              filters:
                - RewritePath=/docs/identity/(?<segment>.*), /$\{segment}

            - id: app-registry-api-route
              uri: lb://app-registry-service
              predicates:
                - Path=/api/apps/**
              filters:
                - AuthenticationFilter
                - RewritePath=/api/apps/(?<segment>.*), /api/$\{segment}
            - id: app-registry-docs-route
              uri: lb://app-registry-service
              predicates:
                - Path=/docs/apps/{*segment}
              filters:
                - RewritePath=/docs/apps/(?<segment>.*), /$\{segment}

            - id: userdata-api-route
              uri: lb://userdata-service
              predicates:
                - Path=/api/user-profile/**
              filters:
                - AuthenticationFilter
            - id: userdata-docs-route
              uri: lb://userdata-service
              predicates:
                - Path=/docs/user-profile/{*segment}
              filters:
                - RewritePath=/docs/user-profile/(?<segment>.*), /$\{segment}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Identity Service
        url: /docs/identity/v3/api-docs
      - name: User Profile Service
        url: /docs/user-profile/v3/api-docs
      - name: App Registry Service
        url: /docs/apps/v3/api-docs
    disable-swagger-default-url: true
  api-docs:
    enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}