  version: '3.8'

  services:
    gateway:
      build: ./gateway
      container_name: gateway
      ports:
        - "${GATEWAY_PORT:-8080}:8080"
      networks:
        - entria-network
      depends_on:
        eureka-server:
          condition: service_healthy
      environment:
        SERVER_PORT: 8080

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:${EUREKA_PORT:-8761}/eureka/

    identity-service:
      build: ./identity-service
      container_name: identity-service
      deploy:
        resources:
          limits:
            memory: 2048M

      ports:
        - "${IDENTITY_SERVICE_PORT}:${IDENTITY_SERVICE_INTERNAL_PORT}"
      networks:
        - entria-network
      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_started
        eureka-server:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
      environment:
        SERVER_PORT: ${IDENTITY_SERVICE_INTERNAL_PORT}

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

        APPLICATION_SECURITY_JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        APPLICATION_SECURITY_JWT_EXPIRATION: ${JWT_EXPIRATION}
        APPLICATION_SECURITY_REFRESH_EXPIRATION: ${REFRESH_EXPIRATION}

        DB_HOST: postgres
        DB_PORT: ${POSTGRES_DB_PORT}
        DB_NAME: ${POSTGRES_IDENTITY_DB_NAME}
        DB_USER: ${POSTGRES_DB_USER}
        DB_PASSWORD: ${POSTGRES_DB_PASSWORD}

        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_PASSWORD: ${REDIS_PASSWORD}

        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_RABBITMQ_PORT: ${RABBITMQ_NODE_PORT}
        SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
        SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}

        APPLICATION_VERIFICATION_CODE_EXPIRATION_IN_SECONDS: ${VERIFICATION_EXPIRATION}
        APPLICATION_VERIFICATION_CODE_LENGTH: ${VERIFICATION_LENGTH}

        APPLICATION_RESET_PASSWORD_CODE_EXPIRATION_IN_SECONDS: ${RESET_PASSWORD_EXPIRATION}
        APPLICATION_RESET_PASSWORD_CODE_LENGTH: ${RESET_PASSWORD_LENGTH}

    app-registry-service:
      build: ./app-registry-service
      container_name: app-registry-service
      deploy:
        resources:
          limits:
            cpus: '1.5'
            memory: 512M
          reservations:
            cpus: '0.25'
            memory: 256M
      ports:
        - "${APP_REGISTRY_SERVICE_PORT}:${APP_REGISTRY_SERVICE_INTERNAL_PORT}"
      networks:
        - entria-network
      depends_on:
        postgres:
          condition: service_healthy
        eureka-server:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
        minio:
          condition: service_healthy
      environment:
        SERVER_PORT: ${APP_REGISTRY_SERVICE_INTERNAL_PORT}

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

        DB_HOST: postgres
        DB_PORT: ${POSTGRES_DB_PORT}
        DB_NAME: ${POSTGRES_APP_REGISTRY_DB_NAME}
        DB_USER: ${POSTGRES_DB_USER}
        DB_PASSWORD: ${POSTGRES_DB_PASSWORD}

        MINIO_URL: http://minio:9000
        MINIO_EXTERNAL_URL: ${MINIO_EXTERNAL_URL:-http://localhost:9000}
        MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
        MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
        MINIO_PUBLIC_BUCKET: entria-public-files

        FRONTEND_AUTHORIZE_URL: ${FRONTEND_AUTHORIZE_URL}


    notification-service:
      build: ./notification-service
      container_name: notification-service
      networks:
        - entria-network
      depends_on:
        rabbitmq:
          condition: service_healthy
      environment:
        SERVER_PORT: ${NOTIFICATION_SERVICE_INTERNAL_PORT}

        SPRING_MAIL_HOST: ${MAIL_HOST}
        SPRING_MAIL_PORT: ${MAIL_PORT}
        SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
        SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}

        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_RABBITMQ_PORT: ${RABBITMQ_NODE_PORT}
        SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
        SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}


    eureka-server:
      build: ./eureka-server
      container_name: eureka-server
      ports:
        - "${EUREKA_PORT:-8761}:8761"
      networks:
        - entria-network
      healthcheck:
        test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health" ]
        interval: 10s
        timeout: 5s
        retries: 5
      environment:
        SERVER_PORT: 8761

    postgres:
      image: postgres:15-alpine
      container_name: postgres
      ports:
        - "${POSTGRES_DB_PORT}:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_DB_USER}
        POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - entria-network
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER}" ]
        interval: 10s
        timeout: 5s
        retries: 5

    # No volume is on purpose, because Redis is used only for caching and does not require data persistence.
    redis:
      image: redis:7-alpine
      container_name: redis
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - entria-network
      command: redis-server --requirepass ${REDIS_PASSWORD}

    redis-commander:
      image: rediscommander/redis-commander:latest
      container_name: redis-commander
      environment:
        - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
      ports:
        - "${REDIS_COMMANDER_PORT}:8081"
      networks:
        - entria-network
      depends_on:
        - redis

    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      ports:
        - "${RABBITMQ_NODE_PORT}:5672"
        - "${RABBITMQ_MANAGEMENT_PORT}:15672"
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
      networks:
        - entria-network
      environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 10s
        timeout: 5s
        retries: 5

    minio:
      image: minio/minio
      container_name: minio
      ports:
        - "9000:9000"
        - "9001:9001"
      command: [ "server", "/data", "--console-address", ":9001" ]
      environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      networks:
        - entria-network
      volumes:
        - minio_data:/data
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
        interval: 10s
        timeout: 5s
        retries: 5

    minio-setup:
      image: minio/mc
      container_name: minio-setup
      depends_on:
        minio:
          condition: service_healthy
      networks:
        - entria-network
      entrypoint: >
        /bin/sh -c "
        /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        /usr/bin/mc mb myminio/entria-public-files --ignore-existing;
        /usr/bin/mc mb myminio/entria-private-files --ignore-existing;
        /usr/bin/mc anonymous set public myminio/entria-public-files;
        exit 0;
        "

  networks:
    entria-network:
      driver: bridge
  volumes:
    postgres_data:
      driver: local
    rabbitmq_data:
      driver: local
    minio_data:
      driver: local